apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: vijay2359/todo-jenkins:latest  # Replace with your actual image if needed
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres-db-service"  # Database hostname (Postgres service name)
            - name: DB_USER
              value: "todo-user"
            - name: DB_PASSWORD
              value: "Vijay2359#"
            - name: DB_NAME
              value: "todo-app"
            - name: DB_PORT
              value: "5432"



